image: node:18  # Usa uma imagem do Node.js compatível

variables:
  ANDROID_HOME: "/opt/android-sdk"
  APPIUM_VERSION: "2.18.0"

stages:
  - setup
  - test

setup-environment:
  stage: setup
  script:
    - echo "Instalando o Appium..."
    - npm install -g appium | tee appium-install.log
    - cat appium-install.log  # Exibe log para depuração
    - export PATH=$(npm bin -g):$PATH
    - sleep 5
    - echo "Verificando instalação..."
    - if ! command -v appium &> /dev/null; then echo "Appium não foi instalado! Abortando."; exit 1; fi
    - which appium
    - appium --version
    - echo "Instalando dependências..."
    - apt-get update && apt-get install -y curl unzip openjdk-17-jdk libgbm1
    - npm install -g codeceptjs  # Instala CodeceptJS globalmente
    - npm install  # Instala todas as dependências do projeto
    - JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))  # Define JAVA_HOME dinamicamente
    - export JAVA_HOME
    - export PATH="$JAVA_HOME/bin:$PATH"
    - echo "Verificando instalação do Java..."
    - java -version
    - echo JAVA_HOME="$JAVA_HOME"

run-tests:
  stage: test
  script:
    - export PATH=$(npm bin -g):$PATH
    - npm install
    - echo "Garantindo que o Appium esteja instalado..."
    - npm install -g appium --unsafe-perm=true --allow-root
    - echo "Iniciando o Appium..."
    - nohup appium --address 127.0.0.1 --port 4723 > appium.log 2>&1 &
    - sleep 30  # Aumente o tempo de espera para garantir que o Appium inicie corretamente
    - echo "Conteúdo do log do Appium:"
    - cat appium.log
    - echo "Verificando conexão com Appium..."
    - curl http://127.0.0.1:4723/status || (echo "Appium não responde, reiniciando..." && pkill -f appium && nohup appium --address 127.0.0.1 --port 4723 > appium.log 2>&1 & sleep 10)
    - echo "Atualizando dependências..."
    - npm audit fix --force
    - npm update
    - echo "Reinstalando Appium-Chromedriver..."
    - npm uninstall appium-chromedriver
    - npm install appium-chromedriver --force
    - echo "Executando os testes..."
    - npx codeceptjs run || (echo "Testes falharam, verificando dependências..." && npm audit fix --force)
  artifacts:
    paths:
      - reports/
    when: always