image: maven:3.8.5

variables:
  ANDROID_HOME: "/opt/android-sdk"
  APPIUM_VERSION: "1.22.0"

stages:
  - setup
  - test

setup-environment:
  stage: setup
  script:
    - echo "Instalando dependências..."
    - apt-get update && apt-get install -y curl unzip
    - echo "Baixando Android SDK..."
    - curl -o android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-11076709_latest.zip
    - ls -lh android-sdk.zip  # Verifica se o arquivo foi baixado corretamente
    - file android-sdk.zip  # Confirma se o arquivo é um ZIP válido
    - unzip android-sdk.zip -d $ANDROID_HOME || echo "Erro ao extrair o SDK"
    - ls -l $ANDROID_HOME/cmdline-tools/  # Confirma que os arquivos foram extraídos
    - export PATH="$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH"
    - chmod +x $ANDROID_HOME/cmdline-tools/bin/sdkmanager  # Ajusta permissões
    - sdkmanager --list  # Confirma se o sdkmanager está funcionando
    - sdkmanager "platforms;android-30" "build-tools;30.0.3" "platform-tools"
    - echo "Instalando Appium..."
    - npm install -g appium@$APPIUM_VERSION
    - appium --version

run-tests:
  stage: test
  script:
    - echo "Iniciando Appium Server..."
    - appium --address 0.0.0.0 --port 4723 > /dev/null 2>&1 &
    - echo "Executando testes..."
    - mvn clean test
  artifacts:
    paths:
      - reports/
    when: always
