image: maven:3.8.5

variables:
  ANDROID_HOME: "/opt/android-sdk"
  APPIUM_VERSION: "1.22.0"

stages:
  - setup
  - test

setup-environment:
  stage: setup
  script:
    - echo "Baixando Android SDK..."
    - curl -o android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
    - ls -lh android-sdk.zip  # Confirma o tamanho do arquivo baixado
    - "[ -s android-sdk.zip ] || echo 'Erro: O arquivo não foi baixado corretamente' && exit 1"
    - unzip android-sdk.zip -d $ANDROID_HOME || echo "Erro ao extrair o SDK"

run-tests:
  stage: test
  script:
    - echo "Iniciando Appium Server..."
    - appium --address 0.0.0.0 --port 4723 > /dev/null 2>&1 &
    - echo "Executando testes..."
    - mvn clean test
  artifacts:
    paths:
      - reports/
    when: always
