image: node:18  # Usa uma imagem do Node.js compatível

variables:
  ANDROID_HOME: "/opt/android-sdk"
  APPIUM_VERSION: "1.22.0"

stages:
  - setup
  - test

setup-environment:
  stage: setup
  script:
    - echo "Baixando Android SDK..."
    - curl -o android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
    - ls -lh android-sdk.zip  # Confirma o tamanho do arquivo baixado
    - mkdir -p $ANDROID_HOME/cmdline-tools/latest  # Garante o diretório correto
    - unzip android-sdk.zip -d $ANDROID_HOME/cmdline-tools/latest || echo "Erro ao extrair o SDK"
    - ls -l $ANDROID_HOME/cmdline-tools/latest/  # Confirma que os arquivos foram extraídos corretamente
    - export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"
    - chmod +x $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager  # Ajusta permissões
    - sdkmanager --list  # Confirma se o sdkmanager está funcionando


run-tests:
  stage: test
  script:
    - echo "Iniciando Appium Server..."
    - appium --address 0.0.0.0 --port 4723 > /dev/null 2>&1 &
    - echo "Executando testes com CodeceptJS..."
    - npx codeceptjs run
  artifacts:
    paths:
      - reports/
    when: always
