image: node:18  # Usa uma imagem do Node.js compatível

variables:
  ANDROID_HOME: "/opt/android-sdk"
  APPIUM_VERSION: "1.22.0"

stages:
  - setup
  - test

setup-environment:
  stage: setup
  script:
    - echo "Instalando dependências..."
    - apt-get update && apt-get install -y curl unzip openjdk-17-jdk
    - JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))  # Define JAVA_HOME dinamicamente
    - export JAVA_HOME
    - export PATH="$JAVA_HOME/bin:$PATH"
    - echo "Verificando instalação do Java..."
    - java -version  # Confirma que o Java está instalado corretamente
    - echo JAVA_HOME="$JAVA_HOME"


run-tests:
  stage: test
  script:
    - echo "Iniciando Appium Server..."
    - appium --address 0.0.0.0 --port 4723 > /dev/null 2>&1 &
    - echo "Executando testes com CodeceptJS..."
    - npx codeceptjs run
  artifacts:
    paths:
      - reports/
    when: always
