image: node:18  # Usa uma imagem do Node.js compatível

variables:
  ANDROID_HOME: "/opt/android-sdk"
  APPIUM_VERSION: "1.22.0"

stages:
  - setup
  - test

setup-environment:
  stage: setup
  script:
    - echo "Instalando o Appium..."
    - npm install -g appium | tee appium-install.log
    - cat appium-install.log  # Exibe log para depuração
    - export PATH=$(npm bin -g):$PATH
    - sleep 5
    - echo "Verificando instalação..."
    - if ! command -v appium &> /dev/null; then echo "Appium não foi instalado! Abortando."; exit 1; fi
    - which appium
    - appium --version
    - echo "Instalando dependências..."
    - apt-get update && apt-get install -y curl unzip openjdk-17-jdk libgbm1
    - npm install -g codeceptjs  # Instala CodeceptJS globalmente
    - npm install  # Instala todas as dependências do projeto
    - JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))  # Define JAVA_HOME dinamicamente
    - export JAVA_HOME
    - export PATH="$JAVA_HOME/bin:$PATH"
    - echo "Verificando instalação do Java..."
    - java -version
    - echo JAVA_HOME="$JAVA_HOME"

run-tests:
  stage: test
  script:
    - echo "Verificando se Appium está rodando..."
    - if ! command -v appium &> /dev/null; then echo "Appium não está instalado! Abortando."; exit 1; fi
    - echo "Confirmando versão do Appium..."
    - which appium
    - appium --version
    - nohup appium --address 0.0.0.0 --port 4723 > appium.log 2>&1 &
    - sleep 10  # Pequeno atraso para garantir inicialização correta
    - echo "Verificando conexão com Appium..."
    - curl --retry 15 --retry-delay 3 --retry-connrefused http://localhost:4723/wd/hub/status
    - echo "Executando os testes..."
    - npx codeceptjs run
  artifacts:
    paths:
      - reports/
    when: always 
