image: node:18  # Usa uma imagem do Node.js compatível

variables:
  ANDROID_HOME: "/opt/android-sdk"
  APPIUM_VERSION: "1.22.0"

stages:
  - setup
  - test

setup-environment:
  stage: setup
  script:
    - echo "Verificando instalando o Appium..."
    - npm install -g appium
    - echo "Iniciando Appium..."
    - appium --version # Confirma que Appium foi instalado corretamente
    - echo "Verificando caminho do Appium..."
    - which appium  # Confirma que o binário está acessível
    - echo "Instalando dependências..."
    - npm install -g codeceptjs  # Instala CodeceptJS globalmente
    - npm install  # Instala todas as dependências do projeto
    - apt-get update && apt-get install -y curl unzip openjdk-17-jdk
    - JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))  # Define JAVA_HOME dinamicamente
    - export JAVA_HOME
    - export PATH="$JAVA_HOME/bin:$PATH"
    - echo "Verificando instalação do Java..."
    - java -version  # Confirma que o Java está instalado corretamente
    - echo JAVA_HOME="$JAVA_HOME"

run-tests:
  script:
    - echo "Verificando se Appium está rodando..."
    - if ! command -v appium &> /dev/null; then echo "Appium não está instalado! Abortando."; exit 1; fi
    - echo "Iniciando Appium..."
    - nohup appium --address 0.0.0.0 --port 4723 > appium.log 2>&1 &
    - sleep 30  # Aguarda tempo suficiente para inicialização
    - echo "Verificando conexão com Appium..."
    - curl --retry 15 --retry-delay 3 --retry-connrefused http://localhost:4723/wd/hub/status
    - echo "Executando os testes..."
    - npx codeceptjs run
  artifacts:
    paths:
      - reports/
    when: always
