image: maven:3.8.5

variables:
  ANDROID_HOME: "/opt/android-sdk"
  APPIUM_VERSION: "1.22.0"

stages:
  - setup
  - test

setup-environment:
  stage: setup
  script:
    - echo "Instalando dependências..."
    - apt-get update && apt-get install -y curl unzip
    - curl -o android-sdk.zip C:\Users\aime_\AppData\Local\Android\Sdk
    - unzip android-sdk.zip -d $ANDROID_HOME
    - export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"
    - sdkmanager "platforms;android-30" "build-tools;30.0.3" "platform-tools"
    - echo "Instalando Appium..."
    - npm install -g appium@$APPIUM_VERSION
    - appium --version

run-tests:
  stage: test
  script:
    - echo "Iniciando Appium Server..."
    - appium --address 0.0.0.0 --port 4723 > /dev/null 2>&1 &
    - echo "Executando testes..."
    - mvn clean test
  artifacts:
    paths:
      - reports/
    when: always

     artifacts:
    paths:
      - reports/
    when: always

