name: Run Mobile Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Instalar Appium
        run: npm install -g appium

      - name: Instalar Android SDK e Ferramentas
        run: |
            sudo apt-get update
            sudo apt-get install -y wget unzip default-jdk
            mkdir -p $ANDROID_HOME/cmdline-tools/latest
            curl -O https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
            unzip -q commandlinetools-linux-10406996_latest.zip -d $ANDROID_HOME/cmdline-tools
            mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
            echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV


      - name: Baixar System Image para Emulador
        run: |
            $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-31;google_apis;x86_64"


      - name: Criar e iniciar emulador
        run: |
            echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test_emulator -k "system-images;android-31;google_apis;x86_64" -d "pixel"
            emulator -avd test_emulator -no-window -gpu swiftshader_indirect &


      - name: Iniciar servidor Appium
        run: appium --log-level info &

      - name: Executar testes
        run: npx codeceptjs run --steps
